### PR TITLE
launch-taiga.sh k8s implementation

### PR DESCRIPTION
**Pull request by sebagarayco**
Base manifests with Deployments and Services to replicate launch-taiga.sh behaviour on Kubernetes clusters..
Simple variable pass with ConfigMap.

This PR might address #6

### CODE REVIEW

**Comment by andrej-pavlov** [comment]
Hello @sebagarayco. I tried to implement your manifests and all is working besides the attachments. The attachments itself are saved to the volumes, but I get a 503 on all attachments urls. I got the advice to put the taiga-protected container in the taiga-back pod (see https://github.com/taigaio/taiga-protected/issues/5), but it's not working either, then i get a 404. 

Do you have an advice how to solve this problem?

**Comment by sebagarayco** [comment]
Hi @andrej-pavlov. I wasn't able to reproduce the error and confirm I could succesfully upload an attachment.

image

Please correct me in the case I'm mistaken and you are referring to another error. Thanks!

**Comment by andrej-pavlov** [comment]
Sorry, I wasn't clear enough. Uploads are fine. But could you please try do download that file again? Or upload an image and click on the title to show it? Thats where taiga-protected comes into play.

**Comment by apvlv** [comment]
Hello @sebagarayco, did you have some time to test it out? Thank you!

**Comment by sebagarayco** [comment]
> Hello @sebagarayco, did you have some time to test it out? Thank you!

Haven't had time yet to troubleshoot this issue. It seems that part of the attachments are downloaded from the taiga-gateway image which I've removed from the Kubernetes manifests.  I'll take a look at it whenever possible. 

Cheers!

**Comment by sebagarayco** [comment]
Hi @volpavo!  
Please give it a try. Attachments previewing should now work properly.

**Comment by nemonik** [comment]
Wish I saw this earlier... I did much of the same work creating a helm chart for hosted here https://github.com/nemonik/taiga-helm

**Comment by apvlv** [comment]
@sebagarayco Yes, can confirm that it's working now as intended! Thank you very much 👍

**Comment by yamila-moreno** [comment]
hi @sebagarayco huge thanks for your contribution.

Currently we're working on [Taiga-Next](https://community.taiga.io/t/announcing-taiganext-and-much-more/107) and Taiga6 cannot accept and give official support to such a big feature.

I encourage you to create a separate repo with the k8s files, and we can link from our official documentation for anyone looking for this.

Cheers!
Yamila

**Pull request closed without merging**
